### ISSUE TITLE
sampgdk warnings

### ISSUE THREAD

**Issue by TommyB123** [Southclaws/pawn-json#2]
I implemented this plugin and experience random sampgdk warnings upon doing various actions. Here's a snippet from my server log.

```[06/15/2020 18:23:22] [connection] incoming connection: 127.0.0.1:53827 id: 1
[06/15/2020 18:23:23] [join] TommyB has joined the server (1:127.0.0.1)
[06/15/2020 18:23:23] [sampgdk:warning] Native function not found: IsPlayerNPC
[06/15/2020 18:23:23] [sampgdk:warning] Native function not found: IsPlayerInAnyVehicle
[06/15/2020 18:23:29] [Login] TommyB
[06/15/2020 18:24:30] [sampgdk:warning] Native function not found: MovePlayerObject
```

Please Help.

**Comment by Alasnkz** [comment]
lol

**Comment by Southclaws** [comment]
Apparently it's a bug with the SDK. Not sure how to fix it.

**Comment by TommyB123** [comment]
After a bit of testing, this seems to be a plugin load order conflict. I loaded the json plugin before the streamer plugin and the problem went away.

**Comment by Southclaws** [comment]
Good to know, thanks!

**Comment by Sreyas-Sreelal** [comment]
That's odd, I couldn't reproduce it whatever the order is.

**Comment by omcho420** [comment]
@Southclaws @Sreyas-Sreelal I don't know any other ppl that have plugins in rust there's finally a fix for this

https://github.com/ZOTTCE/samp-rs/issues/18#issuecomment-649827196

**Comment by Southclaws** [comment]
[pawn_json.zip](https://github.com/Southclaws/pawn-json/files/4956062/pawn_json.zip)

built with the new branch

**Comment by TommyB123** [comment]
this is fixed
