### ISSUE TITLE
How I can read a .json file?

### ISSUE THREAD

**Issue by orsx** [Southclaws/pawn-json#4]
I'm trying to read a .json file but I'm not getting success.

Can you help me?

I have a file called **test.json**
```
{
    "name": "Testing",
    "id": 13,

    "settings": {
        "speed": 70,
        "limit": 150
    },
}

```
```
    new Node:node;
    new ret;

    ret = JsonParse("test.json", node);

```

JsonParse parses a file from scriptfiles?

**Comment by Southclaws** [comment]
https://github.com/Southclaws/pawn-json/blob/master/json.inc#L21

This plugin does not perform any file operations, you have to handle reading yourself.
