### ISSUE TITLE
1.1.0 Plugin don't load in Windows 10

### ISSUE THREAD

**Issue by mreyeshn96** [Southclaws/pawn-json#6]
Problem with pawn-json version 1.1.0:

I have a PC with Windows 10 Single Language of 64 bits, I installed pawn-json by sampctl.
When i execute the server, the plugin don't load:

[20:12:41]  Loading plugin: json
[20:12:41]   Failed.

I tested the plugin by placing it in a different order in server.cfg but I also got the same result in W10.
Since no message appears, I don't know if I should install something additional on my machine, or if it is a problem with the plugin itself.

Also i tried the plugin in Debian 8: don't work.
Also i tried the plugin en Ubuntu 20.04: work correctly.

Thanks.

**Comment by TommyB123** [comment]
Does this DLL work for you?

[json.zip](https://github.com/Southclaws/pawn-json/files/5929272/json.zip)

The Linux build requires a specific glibc version or higher, I believe. I can't remember for certain, but it might be 2.29. I'll look into figuring out static glibc linking later if it's possible. In the meantime, you should consider building the plugin yourself. It's fairly easy to do.

**Comment by mreyeshn96** [comment]
The plugin passed in json.zip works perfectly.
Regarding compiling it myself, I will find a way to do it.
If you happen to have a tutorial to do it, I would appreciate it!

Thank you!!
