### ISSUE TITLE
JSON_Stringify crash server

### ISSUE THREAD

**Issue by continue98** [Southclaws/pawn-json#7]
Hello. JSON_Stringify crash server. I am see code: 
```rust
#[native(name = "JSON_Stringify")]
pub fn json_stringify(
	&mut self,
	_: &Amx,
	node: i32,
	output: UnsizedBuffer,
	length: usize,
) -> AmxResult<i32> {
	let v: &serde_json::Value = match self.json_nodes.get(node) {
		Some(v) => v,
		None => return Ok(1),
	};

	let s = match serde_json::to_string(&v) {
		Ok(v) => v,
		Err(e) => {
			error!("{}", e);
			return Ok(1);
		}
	};

	let mut dest = output.into_sized_buffer(length);
	let _ = samp::cell::string::put_in_buffer(&mut dest, &s);

	Ok(0)
}
```
there is no check for the size of the buffer, and if it is not enough, then there will be overflows and the server will crash

**Comment by ADRFranklin** [comment]
Sorry I don't understand what you mean? The size/length of the string is passed via the native. The length param is what is responsible for that, and `into_sized_buffer` makes sure to cap the size of the output to the length passed in.

**Comment by Southclaws** [comment]
I think it's `put_in_buffer` that's crashing

**Comment by continue98** [comment]
hmm, strange. I can't reproduce it now, but it worked before. If I succeed in doing this, then I will write down here.
